### ISSUE TITLE
4 KB character limit when running in screen

### ISSUE THREAD

**Issue by AlexisEvo** [skaji/remote-pbcopy-iterm2#1]
GNU screen imposes a ~4 KB limit on a single DCS sequence, larger DCS sequences must be sent in chunks. remote-pbcopy-iterm2 currently does not perform this chunking, meaning if the base64 of stdin is larger than ~4 KB, the remainder will be written to stdout instead of written to the clipboard via OSC52.

Example:
```
# works as intended
$ mkpasswd -l 3000 | perl_pbcopy

# nothing is copied to clipboard, anything beyond first 4 KB of base64 data is displayed
$ mkpasswd -l 4000 | perl_pbcopy
NrbmdtbHR2dmVnaHl6dXhldmFhd0p3aHJid3Fza3J0aWJlbnVwcmpxZm5wc2ZucWZhZmpsYmpnbWljaWlxcnlrbHh1am5pcXFnY...
```

The Chromium team has a good reference implementation of this chunking available (in function get_osc52_dsc):

https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/etc/osc52.sh

(OSC_52_MAX_SEQUENCE doesn't seem to apply, at least for iTerm2 + screen -- I've commented out this code and can successfully copy strings that are several MB in size)

iTerm2 build 3.1.1
GNU screen version 4.00.03

**Comment by skaji** [comment]
thanks. I'll look into it.

**Comment by skaji** [comment]
@AlexisEvo Could you try pbcopy in screen branch?
https://github.com/skaji/remote-pbcopy-iterm2/tree/screen
